# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(verbose_name='date updated')),
                ('from_first_name', models.CharField(max_length=60, verbose_name='Sender first name')),
                ('from_last_name', models.CharField(max_length=60, verbose_name='Sender last name')),
                ('from_email', models.CharField(max_length=100, verbose_name='Sender email')),
                ('from_phone', models.CharField(max_length=100, verbose_name='Sender phone')),
                ('to_first_name', models.CharField(max_length=60, verbose_name='Recipient first name')),
                ('to_last_name', models.CharField(max_length=60, verbose_name='Recipient last name')),
                ('delivery_company_name', models.CharField(max_length=60, verbose_name='Company name')),
                ('delivery_first', models.CharField(max_length=100, verbose_name='Address line 1')),
                ('delivery_second', models.CharField(max_length=100, verbose_name='Address line 2')),
                ('delivery_third', models.CharField(max_length=100, verbose_name='Address line 3')),
                ('delivery_postcode', models.CharField(max_length=10, verbose_name='Postcode')),
                ('delivery_note', models.CharField(max_length=200, verbose_name='Gift note')),
            ],
        ),
    ]
