# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, choices=[('I', 'Initiated'), ('S', 'Submitted'), ('F', 'Fulfill'), ('D', 'Dispatched'), ('E', 'Error')], max_length=1),
        ),
    ]
