# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='from_phone',
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_tx',
            field=models.CharField(default='', max_length=100, verbose_name='Stripe tx'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_company_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Gift note'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_second',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_third',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address line 3'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Date created'),
        ),
    ]
