# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20161206_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, choices=[('S', 'Submitted'), ('P', 'Paid'), ('D', 'Dispatched'), ('E', 'Error')], max_length=1),
        ),
    ]
