postgres:
  image: postgres:alpine
  environment:
    POSTGRES_USER: "succulent"
    POSTGRES_PASSWORD: "super"
    PGDATA: "/var/lib/postgresql/data/pgdata"
server:
  build: .
  command: ./run.sh
  env_file: .env
  ports:
    - "8000:8000"
  volumes:
    - .:/app
  links:
    - postgres
